name: Running K6 Load Test - grafana/run-k6-action@v1
run-name: 🏃‍♂️‍➡️ Running K6 Load Test - grafana/run-k6-action@v1
on:
  push:

  workflow_dispatch:
    inputs:
      INPUT_MAX_DURATION:
        description: 'MAX DUARION'
        required: true
        type: choice
        default: '1m'
        options:
          - "30s"
          - "2m"

jobs:
  protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - uses: grafana/run-k6-action@v1
        env:
          BASE_URL: 'https://quickpizza.grafana.com'
          MAX_DURATION: ${{ github.event.inputs.INPUT_MAX_DURATION || '30s'}}
        with:
          path: |
            test.js