name: Running K6 Load Test
run-name: 🏃‍♂️‍➡️ Running K6 Load Test

on:
  pull_request:
    branches:
      - main
  
  workflow_dispatch:
    inputs:
      INPUT_MAX_DURATION:
        description: 'MAX DUARION'
        required: true
        type: choice
        default: '1m'
        options:
          - "30s"
          - "2m"

jobs:
  k6:
    runs-on: ubuntu-latest
    env:
      BASE_URL: 'https://quickpizza.grafana.com'
      MAX_DURATION: ${{ github.event.inputs.INPUT_MAX_DURATION || '30s'}}
   
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1

      - name: Run K6 load test
        run: |
          k6 run -e BASE_URL=${{ env.BASE_URL }} -e MAX_DURATION=${{ env.MAX_DURATION }} test.js